version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 80:80
    links:
      - web

  web:
    image: meanbee/magento2-nginx:1.9
    ports:
      - 80
    links:
      - fpm
      - db
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    #environment:
      #- VIRTUAL_HOST=magento2.docker
      #- VIRTUAL_PORT=80
      #- HTTPS_METHOD=noredirect

  fpm:
    hostname: fpm.magento2.docker
    image: 5bbd3206e92e
    ports:
      - 9000
    links:
      - db
    volumes_from:
      - appdata
    env_file:
      - ./global.env

  db:
    image: mariadb:10
    ports:
      - 3306
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh

  cli:
    hostname: cli.magento2.docker
    image: 7678e89fecc2
    links:
      - db
    tty: true
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      # MAGEDB CONFIGURATION
      - M2SETUP_MAGEDB_BUCKET=test
      - M2SETUP_MAGEDB_DATABUCKET=test2
      - M2SETUP_MAGEDB_REGION=ams3
      - M2SETUP_MAGEDB_SPACE=itonomy-backups
      - M2SETUP_MAGEDB_PROJECT_NAME=magento-demo
      # CLONE URL (external git repository, auth should be handled in global.env or in url itself)
      - M2SETUP_INSTALL_DB=false
      - M2SETUP_INSTALL_EXISTING_DB=true
      - M2SETUP_INSTALL_BRANCH=feature/test-controller
      - M2SETUP_INSTALL_LANGUAGES=nl_NL
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento2.docker/
      # - M2SETUP_SECURE_BASE_URL=https://magento2.docker/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.2.*
      # - M2SETUP_USE_SAMPLE_DATA=true

  cron:
    image: meanbee/magento2-php:7.1-cli
    hostname: magento2-cron.docker
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - appdata
    links:
      - db
    env_file:
      - ./global.env      

  appdata:
    image: tianon/true
    tty: true
    volumes:
      - ./magento:/var/www/magento

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql
